import React from 'react';

const Policies = () => {
  const searchParams = new URLSearchParams(window.location.search);
  const section = searchParams.get('section');

  React.useEffect(() => {
    if (section) {
      const element = document.getElementById(section);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
      }
    }
  }, [section]);

  return (
    <div className="min-h-screen bg-background text-white py-12">
      <div className="max-w-4xl mx-auto px-4">
        <h1 className="text-4xl font-bold mb-2">Policies</h1>
        <p className="text-gray-400 mb-8">Last updated: Jan 2026</p>

        <div className="space-y-8">
          {/* Privacy Policy Section */}
          <section id="privacy-policy">
            <h2 className="text-3xl font-bold mb-4">Privacy Policy</h2>
            <p className="mb-4 leading-relaxed">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="mb-6 leading-relaxed">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <h3 className="text-2xl font-bold mb-4">Interpretation and Definitions</h3>

            <h4 className="text-xl font-bold mb-3">Interpretation</h4>
            <p className="mb-6 leading-relaxed">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h4 className="text-xl font-bold mb-3">Definitions</h4>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc list-inside space-y-2 mb-6">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to <a href="https://www.ebooks24.in/" className="text-blue-400 hover:text-blue-300">https://www.ebooks24.in/</a></li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Karnataka, India</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Website</strong> refers to ebooks24.in, accessible from <a href="https://www.ebooks24.in/" className="text-blue-400 hover:text-blue-300">https://www.ebooks24.in/</a></li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h3 className="text-2xl font-bold mb-4">Collecting and Using Your Personal Data</h3>

            <h4 className="text-xl font-bold mb-3">Types of Data Collected</h4>

            <h5 className="text-lg font-bold mb-3">Personal Data</h5>
            <p className="mb-4 leading-relaxed">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside space-y-2 mb-6">
              <li>Email address</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>

            <h5 className="text-lg font-bold mb-3">Usage Data</h5>
            <p className="mb-4 leading-relaxed">
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="mb-4 leading-relaxed">
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>

            <h5 className="text-lg font-bold mb-3">Information from Third-Party Social Media Services</h5>
            <p className="mb-4 leading-relaxed">
              The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services: Google, Facebook, Instagram, Twitter, LinkedIn.
            </p>

            <h5 className="text-lg font-bold mb-3">Tracking Technologies and Cookies</h5>
            <p className="mb-4 leading-relaxed">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
          </section>

          {/* Use of Your Personal Data */}
          <section className="border-t border-gray-700 pt-8">
            <h3 className="text-2xl font-bold mb-4">Use of Your Personal Data</h3>
            <p className="mb-4 leading-relaxed">
              The Company may use Personal Data for the following purposes: providing and maintaining our Service, managing Your Account, performing contracts, contacting You, providing offers and information, managing Your requests, and evaluating business opportunities.
            </p>
            <p className="mb-4 leading-relaxed">
              We may share Your personal information with Service Providers, business partners, affiliates, and other users in accordance with this Privacy Policy.
            </p>
          </section>

          {/* Retention and Transfer */}
          <section className="border-t border-gray-700 pt-8">
            <h3 className="text-2xl font-bold mb-4">Retention and Transfer of Your Personal Data</h3>
            <p className="mb-4 leading-relaxed">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Your information may be transferred to computers located outside of Your state, province, country or other governmental jurisdiction.
            </p>
            <p className="mb-4 leading-relaxed">
              You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account.
            </p>
          </section>

          {/* Security and Privacy Rights */}
          <section className="border-t border-gray-700 pt-8">
            <h3 className="text-2xl font-bold mb-4">Security and Privacy Rights</h3>
            <p className="mb-4 leading-relaxed">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
            <p className="mb-4 leading-relaxed">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
            </p>
          </section>

          {/* Refund and Returns Policy */}
          <section id="refund-returns" className="border-t border-gray-700 pt-8">
            <h2 className="text-3xl font-bold mb-4">Refund and Returns Policy</h2>
            <p className="mb-4 leading-relaxed">
              Since <a href="https://www.ebooks24.in/" className="text-blue-400 hover:text-blue-300">https://www.ebooks24.in/</a> offers non-tangible irrevocable goods, we do not issue refunds once the order is accomplished. The nature of digital media means that once you have downloaded a product there's no way to 'return' it. All payments at this website are non-refundable.
            </p>
            <p className="mb-4 leading-relaxed">
              Download and unzipping issues: Claims regarding such issues must be submitted within 24 hours. If you do not properly contact us during this period, you agree that we may construe silence as a successful download of the product with no further right of redress or refund. Please contact us on <a href="mailto:info.buysellbooks@gmail.com" className="text-blue-400 hover:text-blue-300">info.buysellbooks@gmail.com</a>
            </p>
          </section>

          {/* Shipping & Cancellation */}
          <section id="shipping-cancellation" className="border-t border-gray-700 pt-8">
            <h2 className="text-3xl font-bold mb-4">Shipping & Cancellation</h2>
            <p className="mb-4 leading-relaxed">
              Shipping is not applicable on this website as we only sell Digital Products. Your orders will be delivered immediately after the purchase to your email.
            </p>
            <p className="mb-4 leading-relaxed">
              Due to the nature of the products, cancellation and refunds are not applicable. Please reach out to us on our support email: <a href="mailto:info.buysellbooks@gmail.com" className="text-blue-400 hover:text-blue-300">info.buysellbooks@gmail.com</a>, and we will solve your queries in less than 24 hours.
            </p>
          </section>

          {/* Terms & Conditions */}
          <section id="terms-conditions" className="border-t border-gray-700 pt-8">
            <h2 className="text-3xl font-bold mb-4">Terms & Conditions</h2>
            <p className="mb-4 leading-relaxed">
              Welcome to <a href="https://www.ebooks24.in/" className="text-blue-400 hover:text-blue-300">https://www.ebooks24.in/</a>
            </p>
            <p className="mb-4 leading-relaxed">
              These terms and conditions outline the rules and regulations for the use of <a href="https://www.ebooks24.in/" className="text-blue-400 hover:text-blue-300">https://www.ebooks24.in/</a> Website. By accessing this website we assume you accept these terms and conditions.
            </p>

            <h4 className="text-xl font-bold mb-3 mt-6">Key Terms and Conditions</h4>
            <ol className="list-decimal list-inside space-y-4 mb-6 ml-4">
              <li><strong>General Information Only:</strong> All content is offered for general informational and educational purposes only. We make no guarantees that the information provided is complete, accurate, reliable, current, or error-free.</li>
              <li><strong>No Liability Disclaimer:</strong> To the maximum extent permitted by law, ebooks24.in shall not be liable for any direct or indirect loss, financial loss, data loss, business loss, or any other damages.</li>
              <li><strong>Accuracy of Information:</strong> We do not warrant or represent that content is always accurate, up-to-date, or suitable for any specific purpose.</li>
              <li><strong>Digital Products & Downloads:</strong> All digital products are provided "as is" and "as available". Once accessed or downloaded, no refunds or exchanges are guaranteed unless explicitly stated.</li>
              <li><strong>Third-Party Links & Content:</strong> We are not responsible for third-party website content, accuracy, policies, or practices.</li>
              <li><strong>No Professional Advice:</strong> Content does not constitute legal, financial, medical, educational, or professional advice.</li>
              <li><strong>Website Availability:</strong> We do not guarantee the Website will be always available, uninterrupted, secure, or free from bugs or viruses.</li>
              <li><strong>Intellectual Property:</strong> All content on this Website is the intellectual property of ebooks24.in. Unauthorized copying, redistribution, resale, or reproduction of any content is prohibited.</li>
              <li><strong>Limitation of Liability:</strong> In no event shall ebooks24.in be liable for any damages exceeding the amount paid by the user for accessing the Website or its products.</li>
              <li><strong>Indemnification:</strong> You agree to indemnify and hold harmless ebooks24.in from any claims, damages, losses, or expenses arising from your use of the Website, violation of these Terms, or misuse of any content or product.</li>
              <li><strong>Changes to Terms:</strong> We reserve the right to update or modify these Terms at any time without prior notice. Continued use of the Website constitutes acceptance of the revised Terms.</li>
              <li><strong>Governing Law & Jurisdiction:</strong> These Terms shall be governed by and interpreted in accordance with the laws of India, and courts located in India shall have exclusive jurisdiction.</li>
            </ol>
          </section>

          {/* Contact */}
          <section className="border-t border-gray-700 pt-8">
            <h2 className="text-3xl font-bold mb-4">Contact Us</h2>
            <p className="leading-relaxed">
              If you have any questions about this Privacy Policy or Terms & Conditions, You can contact us:
            </p>
            <p className="mt-4">
              <strong>Email:</strong> <a href="mailto:info.buysellbooks@gmail.com" className="text-blue-400 hover:text-blue-300">info.buysellbooks@gmail.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Policies;